[package]
name = "haversine"
version = "0.1.0"
edition = "2021"

[features]
profile = ["profiler/profile", "profiler_macro/profile"]

[dependencies]
rand = "0.9.0"
tempfile = "3.18.0"
profiler = { path = "../profiler" }
profiler_macro = { path = "../profiler_macro" }
