[package]
name = "profiler_macro"
version = "0.1.0"
edition = "2021"

[features]
profile = []

[lib]
proc-macro = true

[dependencies]
lazy_static = "1.5.0"
proc-macro2 = "1.0.94"
quote = "1.0.40"
syn = { version = "2.0.100", features = ["full"] }
